import type { Metadata, Viewport } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "#f6f7fb",
  width: "device-width",   // pin layout width to the actual screen
  initialScale: 1,         // render at 1:1, no zoom-to-fit
  viewportFit: "cover",    // safe-area support for the PWA later
};

// Plainhand type: Figtree carries everything — display, body and numerals.
// Numbers align via tabular figures (font-variant-numeric in the StyleBlock)
// rather than a mono face. Exposed as a CSS var consumed by StridePlanner.
const fontBody = Figtree({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stride",
  description: "Generated by create next app",

  appleWebApp: {
     capable: true,
     title: "Stride",
     statusBarStyle: "default",
   },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontBody.variable}>
      <body>{children}</body>
    </html>
  );
}


