import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "#e9e7e1",
  width: "device-width",   // pin layout width to the actual screen
  initialScale: 1,         // render at 1:1, no zoom-to-fit
  viewportFit: "cover",    // safe-area support for the PWA later
};

// Fieldnote type: Space Grotesk carries display + body (weight does the
// hierarchy work), Space Mono carries every numeral. Exposed as CSS vars
// consumed by the StyleBlock in StridePlanner.
const fontBody = Space_Grotesk({
  variable: "--font-body",
  subsets: ["latin"],
});

const fontMono = Space_Mono({
  variable: "--font-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stride",
  description: "Generated by create next app",

  appleWebApp: {
     capable: true,
     title: "Stride",
     statusBarStyle: "default",
   },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontBody.variable} ${fontMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}


