import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "#0d0f0e",
  width: "device-width",   // pin layout width to the actual screen
  initialScale: 1,         // render at 1:1, no zoom-to-fit
  viewportFit: "cover",    // safe-area support for the PWA later
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stride",
  description: "Generated by create next app",

  appleWebApp: {
     capable: true,
     title: "Stride",
     statusBarStyle: "default",
   },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}


